### ISSUE TITLE
the replay complete notification can not be received

### ISSUE THREAD

**Issue by eric4yin** [CESNET/libnetconf#66] opened 2015-06-25 07:10 UTC
When I check the notification replay functionality, the replay complete notification can not be received after subscirbe reply received,

I have review the code, and find there is a mutext session->mut_channel which used by nc_session_receive and notification_send. in above case, the main thread of agent will blocked in nc_session_read_until with lock, so the notication thread can not acquire the lock to send the replay complete notification.

What are your consideration about this mutex in the receive and sent. Can we only use one mutext to protect the send process?

**Comment by rkrejci** [comment] 2015-06-26 08:07
But the calls are not blocking, there are timeouts so it should not stuck for long time. Are you having the problem with Netopeer server or you have your own implementation?

The problem with separating locks for send and receive was on client side when we were using libssh2 and without locking there was race condition problem. The things ahve probably changed with moving to libssh in 0.10.0 version, right @michalvasko ?

**Comment by eric4yin** [comment] 2015-06-26 08:33
@rkrejci yes, in poll function , there is a  timeout with 100ms, but it often blocked in nc_session_read_until wait for the input.

I'm compiling netopeer and libnetconf without libssh2,  to configure subsystem in sshd_config (openssh),

if this situation,  separating locks is still necessay?

**Comment by rkrejci** [comment] 2015-06-26 09:01
Which client do you use? Because nc_session_read_until() is used after polling the channel, so it knows that there are some data from the other side (client in case we are receiving rpc). When you are saying that the function blocks, it means that it gets invalid (in this case probably not terminated) data. 

So, for me, it seems that the problem is actually not in locking, but in data received from the client.

I just tried notification subscription with netopeer-cli and netopeer-server (both netopeer and libnetconf from master branch) and everything works fine for me.

**Closed** 2015-07-28 10:48 UTC
Labels: invalid
